name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer

    - name: Cache Composer Dependencies
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install Dependencies
      run: |
        cd online-dashboard-api && composer install --no-progress --prefer-dist

    - name: Copy .env
      run: |
        cd online-dashboard-api && php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate Application Key
      run: |
        cd online-dashboard-api && php artisan key:generate

    - name: Set Directory Permissions
      run: |
        cd online-dashboard-api && chmod -R 777 storage bootstrap/cache

    - name: Create SQLite Database
      run: |
        cd online-dashboard-api && mkdir -p database && touch database/database.sqlite

    - name: Run Tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: online-dashboard-api/database/database.sqlite
      run: |
        cd online-dashboard-api && php artisan test

    - name: Run Pint (Code Style Fixer)
      run: |
        cd online-dashboard-api && ./vendor/bin/pint --verbose

    - name: Commit Changes (if Pint fixes applied)
      if: ${{ github.event_name == 'push' }} && ${{ steps.pint.outcome == 'success' }}
      run: |
        cd online-dashboard-api && git config --global user.name "GitHub Actions"
        cd online-dashboard-api && git config --global user.email "actions@github.com"
        cd online-dashboard-api && git add .
        cd online-dashboard-api && git commit -m "Apply Pint fixes"
        cd online-dashboard-api && git push
